Added label for remote yoyo code on captive portal and removed text box when none updatable. Also added extra logic to ensure captive portal is in correct setup mode
interactionresearchstudio/ESP32-SOCKETIO pull request #28
Opened 2020-09-22 14:50 UTC by andysheen

2020-09-22 15:13 UTC, mikevanis requested changes
Some suggestions for making it look semantically consistent across all scenarios. My suggestion is that the remote yoyo code should be displayed in the input box and it should be read only.

2020-09-22 15:13 UTC, mikevanis commented on data/index.html
>            <input id="remote-scad-code-input" class="form-control" inputmode="numeric" pattern="[0-9 ]+" type="text" placeholder="Remote Yo-Yo Code">
Add label like this just above the input tag:
```
<label for="remote-scad-code-input">Remote Yo-Yo Code</label>
```

2020-09-22 15:13 UTC, mikevanis commented on data/index.html
>          <div class="mb-4" id="remoteMacForm">
This should also have a class of form-group.
```
<div class="mb-4 form-group" id="remoteMacForm">
```

2020-09-22 15:13 UTC, mikevanis commented on data/script.js
> +
This should modify the remote Yo-Yo code form input to contain the remote mac, but also make the input readonly.
```
if (json.remote_mac != ""){
    $('#remote-scad-code-input').attr('value', formatScadCode(json.remote_mac));
    $('#remote-scad-code-input').attr('readonly', '');
}

2020-09-22 16:38 UTC, mikevanis commented on data/index.html
> +          <p id ="remote-scad-code">XXXX-XXXXX</p>
Ok, so this should be:
```
<p id="remote-scad-text">Remote Yo-Yo Code: <br/><span id="remote-scad-code"></span></p>
```

2020-09-23 08:48 UTC, andysheen commented
updated requests

2020-09-23 08:50 UTC, closed without merging